runtime: nodejs18
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: dist/static

  - url: /assets
    static_dir: dist/assets

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
