name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: myapiproject-deployfirst-1
  REGION: us
  REPO: quicknews-repo
  IMAGE: quicknews-app
  IMAGE_URI: us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry & GCR
        run: |
          gcloud auth configure-docker us-docker.pkg.dev gcr.io --quiet

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI .

      - name: Push to Artifact Registry
        run: |
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE \
            --image $IMAGE_URI \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars VITE_API_URL=https://api.example.com
