name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
            project_id: myapiproject-deployfirst-1
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/myapiproject-deployfirst-1/quicknews-app .

      - name: Push Docker image
        run: |
          docker push gcr.io/myapiproject-deployfirst-1/quicknews-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy quicknews-app \
            --image gcr.io/myapiproject-deployfirst-1/quicknews-app \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars VITE_API_URL=https://api.example.com
